version = 1

test_patterns = ["*_test.go"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/Cyb3r-Jak3/traefikcloudflarejwt"]
  dependencies_vendored = true

[[analyzers]]
name = "test-coverage"
enabled = true