name: Lint & Test
on:
  push:
    paths:
      - 'go.mod'
      - '**.go'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
        - 'go.mod'
        - '**.go'
        - '.github/workflows/lint.yml'

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: "--config .golintci.yml"

  test:
    name: test
    runs-on: ubuntu-latest
    env:
      YAEGI_VERSION: v0.14.3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-  

      - name: Test
        run: go test -v -coverprofile="c.out" -race ./...

      - name: Report to Deepsource
        if: ${{ runner.os == 'Linux' && env.DEEPSOURCE_DSN != null }}
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key go --value-file ./c.out
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

      - name: Install Yaegi ${{ env.YAEGI_VERSION }}
        run: curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b $(go env GOPATH)/bin ${YAEGI_VERSION}

      - name: Run tests with Yaegi
        run: yaegi test -v .
        env:
          GOPATH: ${{ github.workspace }}/go